# Example secrets.toml file for Streamlit Cloud
# Copy this content to the "Secrets" section in Streamlit Cloud advanced settings

UHC_CLIENT_ID = "your-client-id-here"
UHC_CLIENT_SECRET = "your-client-secret-here" 